CREATE DATABASE db_Library
GO
USE db_Library
GO

DROP TABLE BOOK_COPIES
DROP TABLE BOOK_LOANS
DroP TABLE BOOK_AUTHOR
DROP TABLE BORROWER
DROP TABLE LIBRARY_BRANCH
DROP TABLE BOOK
DROP TABLE PUBLISHER

CREATE TABLE PUBLISHER (
	pubName VARCHAR(30) PRIMARY KEY NOT NULL,
	Address VARCHAR(30) NOT NULL,
	Phone VARCHAR(30) NOT NULL
)

CREATE TABLE BOOK (
	BookID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Title VARCHAR(50) NOT NULL,
	pubName VARCHAR(30) CONSTRAINT fk_pubName FOREIGN KEY REFERENCES PUBLISHER(pubName) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE LIBRARY_BRANCH (
	Branchid INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BranchName VARCHAR(30) NOT NULL,
	Address VARCHAR(30) NOT NULL
)

CREATE TABLE BORROWER (
	CardNo INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Name VARCHAR(30) NOT NULL,
	Address VARCHAR(30) NOT NULL,
	Phone VARCHAR(30) NOT NULL
)

CREATE TABLE BOOK_AUTHOR (
	BookId INT CONSTRAINT fk_BookId FOREIGN KEY REFERENCES BOOK(BookId) ON UPDATE CASCADE ON DELETE CASCADE,
	AuthorName VARCHAR(30) NOT NULL
)

CREATE TABLE BOOK_LOANS (
	BookId INT CONSTRAINT fk_BookId2 FOREIGN KEY REFERENCES BOOK(BookId) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT CONSTRAINT fk_BranchID2 FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	CardNo INT CONSTRAINT fk_CardNo FOREIGN KEY REFERENCES BORROWER(CardNo) ON UPDATE CASCADE ON DELETE CASCADE,
	DateOut DATE NOT NULL,
	DueDate DATE NOT NULL
)

CREATE TABLE BOOK_COPIES (
	BookId INT CONSTRAINT fk_BookId3 FOREIGN KEY REFERENCES BOOK(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT CONSTRAINT fk_BranchId3 FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchId) ON UPDATE CASCADE ON DELETE CASCADE,
	No_Of_Copies INT NOT NULL
)


